### ISSUE TITLE
Bug in get_iOS_files

### ISSUE THREAD

**Issue by cassidyschneider** [WIPACrepo/decotools#23]
I tried running get_iOS_files to see if there were any new devices in the data set. It work just fine with the default settings, but then I tried setting include_min_bias=True in case any new phones haven't seen events yet, and I'm getting a weird error when I do this:

Traceback (most recent call last):
  File "getAllDevices.py", line 6, in <module>
    all_files = dt.get_iOS_files(include_min_bias=True)
  File "/home/cschneider/.virtualenvs/deco/lib/python2.7/site-packages/decotools/fileio.py", line 193, in get_iOS_files
    df = get_metadata_dataframe(file_list)
  File "/home/cschneider/.virtualenvs/deco/lib/python2.7/site-packages/decotools/fileio.py", line 57, in get_metadata_dataframe
    xml_dict = xml_to_dict(xml_file)
  File "/home/cschneider/.virtualenvs/deco/lib/python2.7/site-packages/decotools/fileio.py", line 19, in xml_to_dict
    tree = ET.parse(xmlfile)  # Initiates the tree Ex: <user-agents>
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3/RHEL_6_x86_64/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3/RHEL_6_x86_64/lib64/python2.7/xml/etree/ElementTree.py", line 657, in parse
    self._root = parser.close()
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3/RHEL_6_x86_64/lib64/python2.7/xml/etree/ElementTree.py", line 1665, in close
    self._raiseerror(v)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3/RHEL_6_x86_64/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

Any ideas on how to fix this?

**Comment by jrbourbeau** [comment]
It looks like there is an issue when parsing the metadata file. What was the actual command you used that causes this error?

**Comment by cassidyschneider** [comment]
I called dt.get_iOS_files(include_min_bias=True)

**Comment by jrbourbeau** [comment]
Thanks @cschneider6, I got the same error. The metadata file that `get_iOS_files` was having trouble with was actually an empty xml file. I'll work on a fix for dealing with metadata files that exist, but are empty.
